// frontend/src/pages/TermsOfServicePage.jsx
import React from 'react';
import { Link } from 'react-router-dom';

function TermsOfServicePage() {
  return (
    <div className="fade-in max-w-4xl mx-auto bg-slate-800/50 p-8 md:p-12 rounded-2xl shadow-xl border border-slate-700">
      <h1 className="text-4xl font-bold font-serif text-white mb-6">Terms of Service</h1>
      <div className="prose prose-lg max-w-none text-slate-300 prose-headings:text-amber-500 prose-p:leading-relaxed">
        <p><strong>Last Updated: July 31, 2025</strong></p>
        <p>Welcome to Inkwell AI. These Terms of Service ("Terms") govern your use of our website and services. By using our service, you agree to these Terms. <strong>This is placeholder text and not legal advice.</strong></p>

        <h3 className="text-xl font-semibold mt-6 mb-2">1. User Accounts</h3>
        <p>You are responsible for safeguarding your account and for any activities or actions under your account. You agree not to disclose your password to any third party.</p>

        <h3 className="text-xl font-semibold mt-6 mb-2">2. User-Generated Content</h3>
        <p>You retain ownership of the content you create. However, by using our service, you grant Inkwell AI a license to use, store, and process this content to provide and improve our services.</p>

        <h3 className="text-xl font-semibold mt-6 mb-2">3. Prohibited Conduct</h3>
        <p>You agree not to use the service to generate content that is unlawful, defamatory, harassing, abusive, fraudulent, obscene, or is otherwise objectionable.</p>
        
        <h3 className="text-xl font-semibold mt-6 mb-2">4. Limitation of Liability</h3>
        <p>The service is provided "as is." Inkwell AI and its suppliers and licensors hereby disclaim all warranties of any kind. You understand that you use the service at your own discretion and risk. Inkwell AI is not responsible for any content generated by users or AI, including content that may be offensive, inaccurate, or harmful.</p>
      </div>
       <div className="mt-8 border-t border-slate-700 pt-6">
         <Link to="/" className="text-indigo-400 hover:text-indigo-300 transition-colors">
            &larr; Back to Home
         </Link>
       </div>
    </div>
  );
}

export default TermsOfServicePage;